server:
  port: 8849

spring:
  application:
    name: ai-registry
  cloud:
    nacos:
      discovery:
        enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,info


